# Generated by Django 3.2.9 on 2022-09-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(max_length=15)),
                ('open_date', models.DateTimeField(auto_now=True)),
                ('deposit', models.PositiveIntegerField(default=0)),
                ('credit_card', models.PositiveBigIntegerField(default=0)),
                ('debit_card', models.PositiveBigIntegerField(default=0)),
                ('account_type', models.CharField(choices=[('s', 'Savings'), ('c', 'Current')], default='s', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('branch_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('pan_card', models.CharField(max_length=50, unique=True)),
                ('aadhar_card', models.PositiveBigIntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_account', models.CharField(max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('transfer_date', models.DateTimeField(auto_now=True)),
                ('from_balance', models.PositiveIntegerField(default=0)),
                ('to_balance', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('transaction_type', models.CharField(choices=[('WITHDRAW', 'WITHDRAW'), ('DEPOSIT', 'DEPOSIT')], default='DEPOSIT', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
    ]
